[tool.poetry]
name = "yuno-bot"
version = "0.0.1"
description = "basic discod bot"
authors = ["Baka Yuki <yuki@zyradyl.moe>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
discord = "^2.3.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
